import "./globals.css";
import { Sora } from "next/font/google";
import Header from "@/components/view/Header/Header";
import Footer from "@/components/view/Footer";
import ReduxProvider from "@/components/utils/ReduxProvider";
import { ClerkProvider ,auth } from "@clerk/nextjs";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const {userId} = auth()
  
  return (
    <ClerkProvider>
      <ReduxProvider>
        <html lang='en'>
          <body className={sora.className}>
            <Header userId={userId as string} />
            <main>{children}</main>
            <Footer />
          </body>
        </html>
      </ReduxProvider>
    </ClerkProvider>
  );
}
